// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxDPyC8FbFdiKVAk4YRjf8Jev_piw8V8',
    appId: '1:184273810737:web:40a510f8c1324ccef8ec10',
    messagingSenderId: '184273810737',
    projectId: 'sportify-65c85',
    authDomain: 'sportify-65c85.firebaseapp.com',
    storageBucket: 'sportify-65c85.firebasestorage.app',
    measurementId: 'G-2RMCYHQMCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA70HBCQRHBBakpx3et-UdWhB7rdEvbiQ0',
    appId: '1:184273810737:android:342531ffd203b33ff8ec10',
    messagingSenderId: '184273810737',
    projectId: 'sportify-65c85',
    storageBucket: 'sportify-65c85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHHBW4i50f__goAqMMVsgDUcsDLTgi5t8',
    appId: '1:184273810737:ios:8cfa7da994323ed8f8ec10',
    messagingSenderId: '184273810737',
    projectId: 'sportify-65c85',
    storageBucket: 'sportify-65c85.firebasestorage.app',
    iosBundleId: 'com.example.sportifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHHBW4i50f__goAqMMVsgDUcsDLTgi5t8',
    appId: '1:184273810737:ios:8cfa7da994323ed8f8ec10',
    messagingSenderId: '184273810737',
    projectId: 'sportify-65c85',
    storageBucket: 'sportify-65c85.firebasestorage.app',
    iosBundleId: 'com.example.sportifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxDPyC8FbFdiKVAk4YRjf8Jev_piw8V8',
    appId: '1:184273810737:web:5fa082f5619ca888f8ec10',
    messagingSenderId: '184273810737',
    projectId: 'sportify-65c85',
    authDomain: 'sportify-65c85.firebaseapp.com',
    storageBucket: 'sportify-65c85.firebasestorage.app',
    measurementId: 'G-QH5SPJKXXR',
  );
}


